### ISSUE TITLE
Set up CI so that PRs in this repo actually run CI

### ISSUE THREAD

**Issue by gvanrossum** [we-like-parsers/cpython#1]
And merges into the 'pegen' branch should also trigger CI.

Only a basic test run is required -- probably just the standard test suite on macOS, Windows and Linux?

FWIW I have no idea how to do this.

**Comment by pablogsal** [comment]
I have activated Travis CI and GitHub actions, so I think we should be served for now (we will see if the activation was correct once we create a PR).

**Comment by lysnikolaou** [comment]
> I have activated Travis CI and GitHub actions, so I think we should be served for now (we will see if the activation was correct once we create a PR).

I guess, Github Actions would be enough for now. I can rewrite the necessary workflows, as we don't really need to build Docs and we should just run the tests for pegen.

**Comment by pablogsal** [comment]
Opened https://github.com/we-like-parsers/cpython/pull/3 to update the CI files to allow the new "pegen" branch to build.

**Comment by pablogsal** [comment]
> we should just run the tests for pegen.

We should run the full test suite to make sure that the integration works seamlessly, no?

**Comment by lysnikolaou** [comment]
> We should run the full CPython test suite to make sure that the integration works seamlessly, no?

Of course. I meant the pegen branch.

**Comment by lysnikolaou** [comment]
Closed via #3.

**Comment by gvanrossum** [comment]
FYI I've rebased this commit to a more recent master. Hope that doesn't cause anyone too much pain.
