### ISSUE TITLE
Collect perf stats

### ISSUE THREAD

**Issue by gvanrossum** [we-like-parsers/cpython#100]
From @apalala:

> The new parser should compute its performance stats (even at a performance hit) while it is in beta. A switch would make the parser output those stats.
> 
> With that, the parser can issue a Python WARNING for any code with LOC/sec outside of a given threshold (successful or failed parse). 
> 
> The developer who sees the warning will likely know how to follow through (specially if the warning points to a web page).
> 
> Thus we can gather a meaningful case of test cases.
> 
> It's an easy and nice way to go safe about it.

Tricky thing of course is to know what a reasonable speed is for the current computer. Also what timer should we use to avoid mistaking a suspended process for taking so long? ^Z is still a thing. :-)

**Comment by apalala** [comment]
Set a low/optimistic threshold while on the initial betas, and the crowdsourcing reveals what the threshold should be for subsequent betas?

**Comment by gvanrossum** [comment]
The more I think about this the more I fear complications. E.g. what clock to use? What warning mechanism to use? I would feel better if we made it opt-in.

**Comment by apalala** [comment]
Opt-in is perfect for crowdsourcing the test cases.

**Comment by gvanrossum** [comment]
We're not going to do this, sorry.
