### ISSUE TITLE
Using a custom VM for parsing

### ISSUE THREAD

**Issue by gvanrossum** [we-like-parsers/cpython#128]
This is a thought I've had in my head for quite a while now. This is not a fully worked-out design, but I think I can do it. **The big question is, will it actually be faster?** There's overhead for opcode decoding; but there will be significantly less code, and more data and code locality.

My VM design has a stack of Frames representing node invocations, corresponding to the C call stack in the current version (unlike the Python VM, which still uses C stack frames). Each Frame has a reference to a Rule, and some current state including the mark, the cut flag, the current alternative, the next item in that alternative, and list of values to pass into the action. All state that changes during execution of the parser is contained in some Frame, or in the Parser construct (which is unchanged from the current design). A new Frame initialized to all zeros except for the Rule pointer and the initial mark represents the initial state.

Rules are static read-only data structures containing a few flags (mostly related to looping constructs) and an array of Alternatives.

Alternatives are static read-only data structures containing an array of Items and an Action.

Items are actually arrays of opcodes and arguments, or something like that. Most operations either expect a token (by token type) or a rule (by rule ID), but there are a few special opcodes to help with lookaheads, loops, cut and the like (I haven't fully researched the set of special opcodes we'll need, but I think it'll be a handful). The final opcode of each Alternative is always `ACTION`, which causes the Alternative's Action to be executed, passing it the collected values.

Actions are represented as functions (or perhaps a single big C function with a giant switch).

The main execution switch is something like this (I hope you can imagine the data structures from the description above and the code below):
```
top:
  opcode = frame->Rule.alts[frame->alt].items[frame->item++];
  switch (opcode & 0xff) {
  case STRING: v = string_token(p); break;
  // A few others...
  case CUT: frame->cut = 1; goto top;
  case TOKEN: v = expect_token(p, opcode>>8); break;
  case RULE:
    frame = push_new_frame_on_stack(p, rules[opcode>>8]);
    goto top;
  case ACTION:  // Always the last opcode in an alternative
    v = call_action(p, opcode>>8, frame->vals, frame->val);
    frame = pop_frame_from_stack(p);
    goto below;
  }

below:
  if (v) {  // This could be inlined in the cases above
    frame->vals[frame->val++] = v;
    goto top;
  }

next:
  if (frame->cut) goto fail;
  frame->alt++;
  frame->item = 0;
  p->mark = frame->mark;
  if (!frame->Rule.alts[frame->alt]) goto fail;
  goto top;

fail:
  frame = pop_frame_from_stack(p);
  goto next;
```
I have though of a few other opcodes needed related to loops, lookaheads and handling the start rule and overall success or failure; I'll provide more detail later.

**Comment by gvanrossum** [comment]
See the pegenvm branch in we-like-parsing. The code doesn't compile yet, but it's more complete than the above.

**Comment by gvanrossum** [comment]
Status:
- [x] Cut
- [x] Actions
- [x] Optional tokens
- [ ] Optional rules
- [ ] Loop 0
- [ ] Loop 1
- [ ] Loop special: `A.B+`
- [ ] Lookaheads

**Comment by gvanrossum** [comment]
Okay, the first timing results are in! For our infamous xxl.py file:

- old parser: 4.47 seconds
- new parser: 3.22 seconds
- vm parser: 1.84 seconds

Now, the vm parser currently uses a much simpler grammar, because I haven't got parser generating working yet. But still, this gives me hope, because there's also still some perf tuning to be done.

**Comment by gvanrossum** [comment]
Some more systematic timings:

- old parser: 4.49
- new parser: 3.33
- vm parser: 2.00

**Comment by gvanrossum** [comment]
Even more exciting numbers without pydebug!

- old parser: 1.26
- new parser: 1.19
- vm  parser: 0.65

**Comment by pablogsal** [comment]
I am starting to do some benchmarks with `xxl.py` and this are some initial results using Linux perf tool:

![Screenshot from 2020-06-03 09-45-17](https://user-images.githubusercontent.com/11718525/83615884-087c1280-a57f-11ea-8164-379c0532c606.png)


Seems that the switch itself and the branch for the negative lookahead are the most expensive parts of the VM code:

![Screenshot from 2020-06-03 09-46-54](https://user-images.githubusercontent.com/11718525/83616033-3c573800-a57f-11ea-97ce-4998a2c67f6d.png)
![Screenshot from 2020-06-03 09-48-08](https://user-images.githubusercontent.com/11718525/83616111-585ad980-a57f-11ea-8577-682f5ca04108.png)

**Comment by pablogsal** [comment]
Hummmm, it *seems* that the slowdown is due to the extra calls to `_PyPegen_is_memoized`. Parsing `xxl.py` the new parser without the VM calls `_PyPegen_is_memoized` 40373060 times and the VM parser does it 66264588. This is 64% more!! And looking at the previous data, `_PyPegen_is_memoized` is one of the bottlenecks of both parsers!

**Comment by gvanrossum** [comment]
The reason is that the VM doesn't yet have selective memoization!

**Comment by gvanrossum** [comment]
Hm, I implemented selective memoization, and I now measure 318095942 calls. But that's still 8 times your 40373060. What's wrong here?

**Comment by pablogsal** [comment]
> Not even sure how to do that. :-(

I added a new attribute to the parser `p->number_of_calls`, initialize it to 0, add 1 every time you call `_PyPegen_is_memoized ` and print it after the parsing has finished in `_PyPegen_run_parser_from_string` after calling `_PyPegen_vmparser`

**Comment by gvanrossum** [comment]
I'm sorry, I am running out of time -- I need to pack for my trip.

**Comment by pablogsal** [comment]
> Is that code checked in?

No, but you can use this patch:

```diff
diff --git a/Parser/pegen/pegen.c b/Parser/pegen/pegen.c
index 1b4afcec60..715bd58b08 100644
--- a/Parser/pegen/pegen.c
+++ b/Parser/pegen/pegen.c
@@ -681,6 +681,7 @@ _PyPegen_get_memo_statistics()
 int  // bool
 _PyPegen_is_memoized(Parser *p, int type, void *pres)
 {
+    p->calls++;
     if (p->mark == p->fill) {
         if (_PyPegen_fill_token(p) < 0) {
             p->error_indicator = 1;
@@ -1055,6 +1056,7 @@ _PyPegen_Parser_New(struct tok_state *tok, int start_rule, int flags,
     p->mark = 0;
     p->fill = 0;
     p->size = 1;
+    p->calls = 0;

     p->errcode = errcode;
     p->arena = arena;
@@ -1196,9 +1198,11 @@ _PyPegen_run_parser_from_string(const char *str, int start_rule, PyObject *filen

     if (parser_flags & PyPARSE_VMPARSER) {
         result = _PyPegen_vmparser(p);
+        printf("VM parser number of calls: %i\n", p->calls);
     }
     else {
         result = _PyPegen_run_parser(p);
+        printf("Normal parser number of calls: %i\n", p->calls);
     }
     _PyPegen_Parser_Free(p);

diff --git a/Parser/pegen/pegen.h b/Parser/pegen/pegen.h
index 2f9ee7116d..8e3336350c 100644
--- a/Parser/pegen/pegen.h
+++ b/Parser/pegen/pegen.h
@@ -74,6 +74,7 @@ typedef struct {
     growable_comment_array type_ignore_comments;
     Token *known_err_token;
     int level;
+    int calls;
 } Parser;

diff --git a/my_test.py b/my_test.py
new file mode 100644
index 0000000000..904392f526
--- /dev/null
+++ b/my_test.py
@@ -0,0 +1,7 @@
+import _peg_parser
+
+with open('./Tools/peg_generator/xxl.py') as datafile:
+    data = datafile.read()
+
+_peg_parser.parse_string(data, vmparser=True)
+_peg_parser.parse_string(data)
```

and then do:

```
❯ ./python.exe my_test.py
VM parser number of calls: 66264588
Normal parser number of calls: 40373060
```

> I'm sorry, I am running out of time -- I need to pack for my trip.

No problem. Have a great trip!

**Comment by gvanrossum** [comment]
I get
```
VM parser number of calls: 48948561
Normal parser number of calls: 40373060
```
Better than before but still more than the "new" parser.

**Comment by gvanrossum** [comment]
Certainly the parsers don't have exactly the same set of synthesized rules (groups, loop etc.).

For example the VM implements `b.a+` differently -- it is effectively `(a b)* a` which means the final iteration gets halfway into `(a b)`, fails to find `b`, backtracks, and then re-parses to get the single `a`. Hopefully `a` is memoized.

I can't rule out bugs in the memoization code either. Or possibly the list of memoized rules is differently...?

**Comment by gvanrossum** [comment]
Okay, with this adjustment I measure the same number of calls to is_memoized (one more, presumably for the root).

However I still see 50% more insert_memo calls. Running out of time for the investigation though. I'll see if I can push the changes I have so far.

**Comment by gvanrossum** [comment]
In an offline moment I realized the cause is that pop_frame() calls insert_memo() for memoizing rules, and that includes leftrec rules.

I think I have a way to do leftrec without extra or modified opcodes, instead having a separate flag per rule indicating left-recursiveness. It would mean that push_frame() and pop_frame() and and OP_RETURN and 1-2 other places would have to check this flag, but presumably this is still a lot cheaper than calling insert_memo() redundantly.

I do worry whether the project is doomed if the memo operations dominate the runtime this much.

**Comment by gvanrossum** [comment]
Alas, after making it use the full grammar, it's actually slower:

- old parser: 1.33
- new parser: 1.22
- vm  parser: 2.05

I'm going to give up on this idea.
