### ISSUE TITLE
Remove the old parser

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#134]
Now that beta3 is out and beta4 is scheduled for the end of June, should we maybe start working on removing the old parser? I know @pablogsal already had something in the making, but I guess the review along with things that may need improving will take time.

**Comment by pablogsal** [comment]
I opened this draft PR with the rebased version of the commit I have started https://github.com/python/cpython/pull/20768

**Comment by gvanrossum** [comment]
I suppose that's reasonable.

**Comment by lysnikolaou** [comment]
python#20768 is now merged!
