### ISSUE TITLE
Hand-written extension module in Tools/peg_generator

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#14]
I'm gonna take a short break, so I'm writing down what we left out of #11, now that I still got everything fresh.

**Comment by lysnikolaou** [comment]
For a lack of a better place, I'll ask this here. Wouldn't it be better to remove all the duplicate code and abandon the idea of generating an extension module in cpython?

If we want to try things out, we can always do that in the pegen repo. And since we now have `test_peg_parser` in the stdlib tests to test things, I can't see why we want to have all those duplicates in Tools/peg_generator.

**Comment by gvanrossum** [comment]
That is actually a very good observation! Maybe we can first port the structural changes from Tools/peg_generator/ to the pegen repo (this should mostly be related to moving the C code from pegen/ to peg_parser/).

**Comment by lysnikolaou** [comment]
I'm also down-porting the run_parser* rewrite as well and I am wondering if we should hand-write the C extension module in pegen as well. If we do so, then things like `@modulename` do not work.

**Comment by gvanrossum** [comment]
I don't think we really need `@modulename` anyway.
