### ISSUE TITLE
Are we allowing space between '!' and 'r/a/s'?

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#196]
Had a brief discussion with Mark and Guido during the sprints earlier this month on this, and the feeling I got is that we shouldn't allow this. What do you think?

**Comment by pablogsal** [comment]
I concur, I think there is no good reason to offer more flexibility here. The only question is how hard is this to implement

**Comment by lysnikolaou** [comment]
Oh, it turns out this is already implemented here!
https://github.com/we-like-parsers/cpython/blob/09e77326574c046219c946bba34b098f0a682bb4/Parser/action_helpers.c#L1074-L1084

So, just close this and leave it as is?

**Comment by pablogsal** [comment]
I'm +1 on that. @isidentical ?

**Comment by isidentical** [comment]
Yep, makes perfect sense to me.
