### ISSUE TITLE
Re-enable [macOS and] Windows tests

### ISSUE THREAD

**Issue by gvanrossum** [we-like-parsers/cpython#20]
These were disabled temporarily in #19 but it's still unclear why they would fail.

**Comment by gvanrossum** [comment]
MacOS tests were done in #26. Windows still to do.

**Comment by gvanrossum** [comment]
Can't we close this?

**Comment by pablogsal** [comment]
I have set-up https://github.com/we-like-parsers/cpython/pull/82 to close this once is merged
