### ISSUE TITLE
When should we start the discussion on python-dev?

### ISSUE THREAD

**Issue by pablogsal** [we-like-parsers/cpython#30]
When do you think is a good time to post the PEP on python-dev?

**Comment by gvanrossum** [comment]
Let's wait until it's no longer April 1st AOE.

**Comment by lysnikolaou** [comment]
> Let's wait until it's no longer April 1st AOE.

Good point.

**Comment by lysnikolaou** [comment]
It's now (at least) April 2nd AOE. Shall we start the discussion now?

**Comment by gvanrossum** [comment]
I've got some time, I'll send a message right now.

**Comment by gvanrossum** [comment]
https://mail.python.org/archives/list/python-dev@python.org/thread/HOZ2RI3FXUEMAT4XAX4UHFN4PKG5J5GR/

**Comment by gvanrossum** [comment]
I also updated the PEP's headers to set python-version to 3.9 and post-history to today.
