### ISSUE TITLE
Run both parsers and compare output

### ISSUE THREAD

**Issue by gvanrossum** [we-like-parsers/cpython#33]
On python-dev, Nathaniel just suggested that we could run both the old and the new parser and compare the trees, at least during the alpha/beta period. This would help us trust that the new compiler fulfills its promise. (When selecting the old parser we should not do this, of course. Some people may be testing for startup speed, for example.)

**Comment by pablogsal** [comment]
Isn't a flavour of this already being done with `test.test_peg_parser.ASTGenerationTest`?

**Comment by lysnikolaou** [comment]
If I understand Nathaniel correctly, he proposes to always parse with both parsers, if `-pnew` is passed as a flag, and compare the trees, before going on to execute the file/command/module. If that's indeed the case, there are two questions, that need to be answered:

1. What do we do, if the trees do not match? Emit a warning that encourages the user to file a report on bpo? I don't think I've ever seen that.
2. I don't really know, how easy it would be to compare two tree in C-level. I guess, it could lead to the interpreter being a bit slower at the very least.

Then again. maybe I've misunderstood and all of this is just irrelevant.

**Comment by gvanrossum** [comment]
As long as the default is `-p old` we should probably fail hard, to get people's attention.

Once the default is `-p new` maybe we can copy whatever behavior Black uses? It does a similar check to ensure that the AST is the same before and after reformatting the code. I've never seen it fail so I don't actually know what it does.

If we go this way, maybe the code for comparing two trees can be generated by the ASDL machinery (which generates the data structures and code for AST creation)?

**Comment by lysnikolaou** [comment]
Closing this, since the discussion during the Language Summit made it clear, that we'll not implement it!
