### ISSUE TITLE
Command-line flag to enable and disable the new parser

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#4]
- [ ] Add a non-functional flag to begin with.
- [ ] Implement the needed functionality, so that enabling the flag has the desired effect.

**Comment by lysnikolaou** [comment]
I've been playing around with CPython, in order to somewhat learn the code that parses command-line options. I tried out adding a `case 'p'` in the switch statement in [`config_parse_cmdline`](https://github.com/python/cpython/blob/21da76d1f1b527d62b2e9ef79dd9aa514d996341/Python/initconfig.c#L1850), but that doesn't seem to work by itself. Could you tell me which files should I be looking into?

**Comment by pablogsal** [comment]
You need to do the proper modifications in `Python/getopt.c` first. Particularly start here:

https://github.com/python/cpython/blob/master/Python/getopt.c#L44
