### ISSUE TITLE
Change SyntaxError messages to match the current parser

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#43]
Wherever the current parser outputs a specialized error message, we ought to do so as well. Not clear how exactly we are going to implement this yet. There's @pablogsal's proposal from [#41 (comment)](https://github.com/we-like-parsers/cpython/pull/41#issuecomment-609130727).

**Comment by pablogsal** [comment]
I was reading today about labelled failures in PEG parsers (https://arxiv.org/abs/1405.6646) as a technique to produce meaningful error messages. Seems that is not to complex to implement in the generator so maybe this is something worth exploring.

The gist (as I understand the technique) is that currently a rule can fail to parse and as we know that means that another rule can be tried instead. Labelled failures allow to have multiple ways of failing. For instance, failing to parse a specific rule can set a label (a global indicator for instance) and other rules can inspect said inducator and make choices about it like propagating it, changing it to some other or emmit a success or a failure. At the end of the program, if the parsing failed and there is a label, the parser can emmit a specialized error message associated with that label.

What do you think?

**Comment by lysnikolaou** [comment]
This is really interesting! Personally, I wasn't really into invalid syntax rules in the grammar file itself, but it seemed like we had to do it. With this, we can go back to what we had before, but with more meaningful error messages.

I'll read up on the paper in more detail first thing in the morning and I'll come back with some more comments.

As I said yesterday as well, I'll have a bunch of time in the following weeks, so I'm up for working on this, should we decide to go for it.

**Comment by gvanrossum** [comment]
Good find, Pablo!

Before we dive too deeply into this, maybe we should walk through a simple example for our own grammar (I personally learn much better from examples than from papers :-).

On python-dev someone remarked that the grammar is not actually simpler than the old grammar (even with the actions taken out). I hope that this approach can make our grammar simpler (after cleaning it up).

**Comment by lysnikolaou** [comment]
So, first of all, I also have to say very good find, Pablo! Thanks again. 

I read the whole paper and I'm going to try to sum up my understanding of it and how and when I think we could implement it here, so please bear with me.

In order to have support for the whole error-reporting system proposed in the paper we have to implement the following four new features:

1. A new parametrized `throw` operator, similar to the `cut` operator, that throws an exception. It accepts a label as a parameter, which is the type of the exception thrown.
2. A parametrized `alt` operator, similar to the already implemented `|` operator. It accepts a list of labels as a parameter. `p1 |(label1, label2) p2` (not proposing this syntax) means that the parser tries to parse `p1` and only tries to parse `p2`, if `p1` failed with one of the exceptions represented by the labels `label1` or `label2`.
3. The ability to parametrize terminal nodes, like keywords or puntuation marks. All terminal nodes should be able to accept a label as a parameter, like `'if'(label)`. If the node fails, then the rule should fail setting the corresponding label as the exception type.
4. A global parser error state, maybe similar to perrdetail, which holds the current error label, the token which failed to parse and its position and maybe other things. To contemplate this, we have to implement a global mapping between exception types (labels) and corresponding error messages.

This is really a very nice error-handling mechanism and would a great enhancement to pegen and `SyntaxError` reporting in Python in general. It'd give pegen the ability to report errors, the old one didn't, like missing colons and such. I'd be more than happy to work on implementing it.

BUT here come the (not so) bad news. I don't think we should strive to implement this before alpha6 (or even beta1). And here's why. (I'll try my best to explain myself, if I don't succeed in being close to understandable, please tell me so and I'll try again) 

Our top priority right now is the error messages we are trying to "copy" from the current parser, since our goal is to match the old parser before we go on to build on and report errors the old parser didn't. Most of these, however, rely on things being accepted by the parser, only to get declined by the hand-written CST-to-AST tranlation code. And that means that this code has access to information, our parser is not going to have access to, if we only fail to parse things (even if we are using the afore-mentioned advanced constructs to do so) and not accept anything. In order to acquire that information, we will have to parse invalid syntax as valid, so that we get to the action code, like Pablo proposed.

One very good example of this is the error message, when an expression, which is not a NAME, is parsed as part of an assignment expression. The code in ast.c looks like this:
```
if (target->kind != Name_kind) {
    const char *expr_name = get_expr_name(target);
    if (expr_name != NULL) {
        ast_error(c, n, "cannot use assignment expressions with %s", expr_name);
    }
    return NULL;
}
```
We could never do something like that, except if we actually parse that target as an expression, after we've tried out NAME and it failed. That means that we would have to do something like this:
```
named_expression[expr_ty]:
    | a=NAME ':=' b=expression { _Py_NamedExpr(CHECK(set_expr_context(p, a, Store)), b, EXTRA) }
    | a=expression ':=' { raise_syntax_error(p, "cannot use assignment expressions with %s", get_expr_name(a)) }    
    | expression
```

This is what I've gathered from going through the paper and giving it some thought. I hope I've not missed something important and this is indeed relevant.

**Comment by gvanrossum** [comment]
I haven't read the paper but your summary and conclusion ring true about this subject. The solution you have for named_expression seems reasonable -- we can do this for a few other places too I presume. (In particular, keyword args and regular assignments to bad targets.)

**Comment by lysnikolaou** [comment]
I'm closing this, since I opened separate issues for the remaining test failures.
