### ISSUE TITLE
Segfault while parsing the invalid assignment `a = 'hello`

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#47]

**Comment by lysnikolaou** [comment]
Turns out this is due to memoizing the `star_targets` rules. What's happening is the following:

1. `p->mark` is 0 at first 
2. The parser goes down to `star_atom`, parses the identifier and p->mark is now 1.
3. The `=` sign is parsed in the rule `star_targets '='` and p->mark gets the value 2.
4. The parser gets back to the loop `(star_targets '=')+`, succeeds and tries to memoize the result. In the `insert_memo` function `p->tokens[mark]->memo` segfaults, since mark is 2, but the third token has not been inserted to the token array.

I don't really know why this is happening yet or what the correct solution is, but I'm working on it.

**Comment by pablogsal** [comment]
I assume this also happens when we were memoising all the rules, no?

**Comment by lysnikolaou** [comment]
> I assume this also happens when we were memoising all the rules, no?

Yeah, this has been there all along.
