### ISSUE TITLE
Provide column info on EOF and EOL errors (and others if possible)

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#50]
See [#42 (comment)](https://github.com/we-like-parsers/cpython/pull/42#discussion_r403774122).

**Comment by lysnikolaou** [comment]
It seems, the current parser uses `perrdetail` to point to a specific column on these errors, which we
don't (yet) and there's really no info in the tokenizer struct.

**Comment by gvanrossum** [comment]
So I'm guessing we'll have to thread this through a bunch of APIs and set it? It looks like certain APIs for parsing things take a `perrdetail *err_ret` and use this to return details about the error; the caller has to declare a local `perrdetail err` and pass its address into the function. We can do that too I suppose.

**Comment by lysnikolaou** [comment]
Yes, that would be the way to go, but there is one question. The error handling function `err_input` is a function local to `pythonrun.c`. In order to be able to use it, we either have to export or move the `PyPegen_*` C API functions to `pythonrun.c`. What do you think would be best here?

I think this is a good improvement, because it could work well with the error-reporting system described in the paper Pablo found.

**Comment by gvanrossum** [comment]
There already seems to be a public wrapper for `err_input`, `PyParser_SetError`. Also, for `err_free` there's `PyParser_ClearError`.
