### ISSUE TITLE
Failure in test_fstring: SyntaxError messages are different

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#66]
There are two fstring-related types of `SyntaxError`s, where pegen produces a different kind of error message:

1. Invalid string prefixes: For invalid string prefixes we output `invalid syntax`, while the old parser outputs `unexpected EOF while parsing`, which is arguably wrong.

2. For lambdas inside fstring expressions it's exactly the same. Pegen outputs `invalid syntax`, while the old parser prints `unexpected EOF while parsing`, which again is arguably wrong.

For some reason, I can't reproduce these error messages in an interactive session, but the tests pass with the old parser and fail with pegen, both on my systam and on Github Actions.

**Comment by lysnikolaou** [comment]
As soon as I posted this, I found this out:

With the old parser:
```
╰─ ./python 
Python 3.9.0a5+ (heads/pegen:99a8e2fa08, Apr  9 2020, 16:19:04) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> fur''
  File "<stdin>", line 1
    fur''
       ^
SyntaxError: invalid syntax
>>> eval("fur''")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    fur''
       ^
SyntaxError: unexpected EOF while parsing
```

**Comment by gvanrossum** [comment]
Let’s fix the old parser.

**Comment by lysnikolaou** [comment]
Open a bug report on bpo: https://bugs.python.org/issue40246

**Comment by lysnikolaou** [comment]
Since python/cpython#19476 is now merged, there is only one remaining error in test_fstring:

Current parser:
```
╰─ ./python
Python 3.9.0a5+ (heads/pegen-dirty:8a3e8a366a, Apr 12 2020, 22:40:08) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> f'{lambda x:x}'
  File "<fstring>", line 1
    (lambda x)
             ^
SyntaxError: unexpected EOF while parsing
```

Pegen:
```
╰─ ./python -p new 
Python 3.9.0a5+ (heads/pegen-dirty:8a3e8a366a, Apr 12 2020, 22:40:08) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> f'{lambda x:x}'
  File "<fstring>", line 1
    (lambda x)
             ^
SyntaxError: invalid syntax
```

**Comment by lysnikolaou** [comment]
Just noticed this:

```
╰─ ./python       
Python 3.9.0a5+ (heads/pegen-dirty:8a3e8a366a, Apr 12 2020, 22:40:08) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> f'{lambda x:x}'
  File "<fstring>", line 1
    (lambda x)
             ^
SyntaxError: unexpected EOF while parsing
>>> (lambda x)
  File "<stdin>", line 1
    (lambda x)
             ^
SyntaxError: invalid syntax
```

**Comment by gvanrossum** [comment]
I'd file a bpo bug for that too; I wonder if Eric V Smith might have an opinion on this (IIRC the f-string implementation is largely his). Using examples like `x+` it seems all too easy to elicit different error messages in different contexts (e.g. eval() vs. exec()).

**Comment by lysnikolaou** [comment]
Pushed python#19521.
