### ISSUE TITLE
Do we need the peg_parser module?

### ISSUE THREAD

**Issue by pablogsal** [we-like-parsers/cpython#83]
If the new parser is going to be the default (and therefore `ast.parse` and `compile`) will use it, do we really need the `peg_parser` module? 

I am asking because I was going to make it compile on Windows, but if we are not going to keep it around, it does not make sense to make the effort.

**Comment by gvanrossum** [comment]
I think we'll still need it. I would like there to be a way to select which parser to use for a specific input string regardless of the `-p` flag. The `peg_parser` module would be that API for the new parser. I guess the old `parser` module would be it for the old parser?

IMO we need these just so we can write tests for both parser. How else would you write a test that compares the AST produced by the old and the new parser for a given file?

**Comment by pablogsal** [comment]
> How else would you write a test that compares the AST produced by the old and the new parser for a given file?

We could record the output of the old parser and read that from a file or something, but I do agree that this is suboptimal and still does not allow to run with the parser you want regardless of the `-p` flag.

**Comment by pablogsal** [comment]
Should we make it "private"? (Naming it `_peg_parser` instead of `peg_parser`)

**Comment by lysnikolaou** [comment]
I'm for making it private, in order to discourage folks from using this instead of `ast.parse`.

**Comment by gvanrossum** [comment]
Sure, that way we can kill in in 3.10.

**Comment by pablogsal** [comment]
Ok, will do a PR after we merge https://github.com/we-like-parsers/cpython/pull/82
