### ISSUE TITLE
Fix Travis for upstream CPython

### ISSUE THREAD

**Issue by pablogsal** [we-like-parsers/cpython#85]
In upstream CPython, the Travis configuration uses Python 3.5 (for real) when running regeneration steps (PYTHON_FOR_REGEN) and that fails due to f-strings and other stuff in our generator. We need to upgrade the Travis file to use something more modern so the ci does not fail when merging upstream.

We should also restore all ci files that are used upstream so we know we are not missing something more.

**Comment by lysnikolaou** [comment]
Closing this now that #88 is merged.
