### ISSUE TITLE
test_peg_parser should always use both parsers

### ISSUE THREAD

**Issue by pablogsal** [we-like-parsers/cpython#93]
Now that we use `pegen` by default, `test_peg_parser` is not using the old parser to compare the produced AST trees (because `ast.parse` also uses the new parser). We need to make sure that the test always compares both parsers against each other (maybe exposing the old parser also in the new `_peg_parser` module).

**Comment by lysnikolaou** [comment]
Very good catch!

> maybe exposing the old parser also in the new _peg_parser module

How could we go about doing this?

One other alternative would be to use a child process: `./python -X pold -m ast`, right?

**Comment by gvanrossum** [comment]
There are many issues with using a subprocess.

I like the idea of adding functions for this to _peg_parser, look at compile() how to do it. (But simplify.)

**Comment by lysnikolaou** [comment]
Fixed in python/cpython#19778.
