### ISSUE TITLE
Add a use_peg field to PyCompilerFlags

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#94]
Would it be too much to add a `cf_use_peg_parser` field to `PyCompilerFlags`? I think it'd make things simpler for #93 and we wouldn't need the not so pretty `_PyInterpreterState_GET()->config` assignment in pythonrun.c.

**Comment by pablogsal** [comment]
> Would it be too much to add a `cf_use_peg_parser` field to `PyCompilerFlags`?

I would personally prefer to have less amount of flags possible, given that we are going to remove them in the future. But on the other hand, if that makes things much easier, then I won't mind that much.

**Comment by gvanrossum** [comment]
I'll leave this to you both.

**Comment by lysnikolaou** [comment]
@pablogsal I was thinking of writing a function to initialise the compiler flags based on the config value, thus minimising the number of calls to `_PyInterpreterState_GET()`.

I went ahead and quickly went through what would need changing, in order to better assess the burden of having to remove the compiler flag in the next release and I think you're right. It a bit more work with no significant benefits.

I'm closing this.

**Comment by pablogsal** [comment]
Thanks @lysnikolaou for doing the investigation!
